name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 099014799395.dkr.ecr.ca-central-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t majid-api .
          docker tag majid-api:latest 099014799395.dkr.ecr.ca-central-1.amazonaws.com/majid-api:latest
          docker push 099014799395.dkr.ecr.ca-central-1.amazonaws.com/majid-api:latest

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster majid-cluster --service majid-service --force-new-deployment
